#!/bin/bash
# =============================================================================
# deploy.sh  —  runs on EC2-B as the ubuntu user
# Called by Jenkins:  deploy.sh <BUILD_TAG>
#
# What it does:
#   1. Loads the .env file so all config values are available
#   2. Writes the Spring Boot application.properties from .env values
#   3. Symlinks the new JAR as the active release
#   4. Copies the React dist to the nginx web root
#   5. Installs / updates nginx, prometheus, grafana configs
#   6. Restarts only the services that changed
#   7. Keeps the last 3 releases and removes older ones
# =============================================================================

set -euo pipefail

BUILD_TAG="${1:?Usage: deploy.sh <BUILD_TAG>}"
DEPLOY_DIR="/opt/sms"
RELEASES_DIR="${DEPLOY_DIR}/releases"
ACTIVE_JAR="${DEPLOY_DIR}/sms-backend-active.jar"
NGINX_ROOT="/var/www/sms"
APP_PROPS="/etc/sms/application.properties"
ENV_FILE="${DEPLOY_DIR}/.env"

log() { echo "[deploy] $*"; }

# =============================================================================
# 1. Load .env
# =============================================================================
log "Loading environment from ${ENV_FILE}..."
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "ERROR: ${ENV_FILE} not found. Jenkins should have copied it." >&2
  exit 1
fi
# Export each non-comment, non-empty line
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

# =============================================================================
# 2. Write application.properties for Spring Boot
#    Spring Boot reads this file at startup. All secrets come from .env,
#    never from the git repository.
# =============================================================================
log "Writing application.properties..."
sudo mkdir -p /etc/sms
sudo tee "${APP_PROPS}" > /dev/null << PROPS
# Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") — do not edit manually
spring.application.name=student-management-system
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/sms_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=${CORS_ORIGINS}

# Actuator / Monitoring
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
PROPS
sudo chmod 640 "${APP_PROPS}"
sudo chown ubuntu:ubuntu "${APP_PROPS}"

# =============================================================================
# 3. Symlink the new JAR as the active release
# =============================================================================
NEW_JAR="${RELEASES_DIR}/sms-backend-${BUILD_TAG}.jar"
if [[ ! -f "${NEW_JAR}" ]]; then
  echo "ERROR: JAR not found: ${NEW_JAR}" >&2
  exit 1
fi

log "Activating release ${BUILD_TAG}..."
ln -sf "${NEW_JAR}" "${ACTIVE_JAR}"

# =============================================================================
# 4. Copy React dist to nginx web root
# =============================================================================
log "Deploying frontend..."
sudo mkdir -p "${NGINX_ROOT}"
sudo rsync -a --delete "${DEPLOY_DIR}/frontend/dist/" "${NGINX_ROOT}/"
sudo chown -R www-data:www-data "${NGINX_ROOT}"

# =============================================================================
# 5. Install nginx site config
# =============================================================================
log "Installing nginx config..."
sudo cp "${DEPLOY_DIR}/sms.conf" /etc/nginx/sites-available/sms
sudo ln -sf /etc/nginx/sites-available/sms /etc/nginx/sites-enabled/sms
# Remove the default nginx site if still present
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t   # validate config before reloading

# =============================================================================
# 6. Install prometheus config
# =============================================================================
log "Installing Prometheus config..."
sudo cp "${DEPLOY_DIR}/monitoring/prometheus.yml" /etc/prometheus/prometheus.yml

# Install Grafana datasource provisioning
sudo mkdir -p /etc/grafana/provisioning/datasources
sudo cp "${DEPLOY_DIR}/monitoring/grafana/provisioning/datasources/prometheus.yml" \
        /etc/grafana/provisioning/datasources/prometheus.yml

# =============================================================================
# 7. Restart / reload services
# =============================================================================
log "Restarting services..."
sudo systemctl restart sms-backend
sudo systemctl reload  nginx
sudo systemctl restart prometheus
sudo systemctl restart grafana-server

# node_exporter runs as a static exporter — only restart if not running
sudo systemctl is-active --quiet node_exporter \
  || sudo systemctl start node_exporter

# =============================================================================
# 8. Prune old releases — keep only the last 3
# =============================================================================
log "Pruning old releases..."
ls -t "${RELEASES_DIR}"/sms-backend-*.jar 2>/dev/null \
  | tail -n +4 \
  | xargs -r rm -f

log "✅ Deploy of build #${BUILD_TAG} complete"
log "   JAR     : ${NEW_JAR}"
log "   Frontend: ${NGINX_ROOT}"
log "   Services: sms-backend nginx prometheus grafana-server node_exporter"
